language: node_js

addons:
  code_climate:
    repo_token: bf670fe192fdc64141c8e6c29042ee4e7337753465252d73f78e27a59cbc037d

before_script:
  - npm install -g istanbul

after_success:
  - npm install -g codeclimate-test-reporter
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage && rm -rf ./coverage
